r"""
데이터베이스(DB)예요. 회원 정보와 대화 기록을 저장해요.

  - 내 컴퓨터: SQLite (파일 하나, data/ssayuz.db). Python에 기본으로 들어 있어요.
  - 인터넷 서버: Postgres (Neon 무료 DB). 환경 변수 DATABASE_URL 이 있으면 이쪽을 써요.
    무료 서버(Render)는 다시 켜질 때마다 파일이 지워져서, DB를 바깥(Neon)에 둬야 기록이 남아요.

표(테이블) 3개:
  users         : 회원 (아이디, 비밀번호를 알아볼 수 없게 바꾼 값)
  conversations : 대화방 (누구의 대화인지, 제목)
  turns         : 질문 하나와 그 답 (검색 기록)
"""

import datetime
import json
import os
import sqlite3
import ssl
from contextlib import contextmanager
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

# 데이터를 저장하는 폴더. 시험할 때는 SSAYUZ_DATA_DIR 로 다른 폴더를 쓸 수 있어요
DATA_DIR = Path(os.environ.get("SSAYUZ_DATA_DIR", Path(__file__).parent / "data"))
DB_PATH = DATA_DIR / "ssayuz.db"
# Postgres 주소 (Neon 의 'Connection string'). 비어 있으면 SQLite 를 써요
DATABASE_URL = os.environ.get("DATABASE_URL", "")

SQLITE_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id            INTEGER PRIMARY KEY,
    username      TEXT    NOT NULL UNIQUE COLLATE NOCASE,  -- 대소문자가 달라도 같은 아이디로 봐요
    password_hash TEXT    NOT NULL,                        -- 비밀번호 원래 글자는 저장하지 않아요
    created_at    TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS conversations (
    id         INTEGER PRIMARY KEY,
    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title      TEXT    NOT NULL,
    created_at TEXT    NOT NULL,
    updated_at TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_conversations_user ON conversations(user_id, updated_at);

CREATE TABLE IF NOT EXISTS turns (
    id              INTEGER PRIMARY KEY,
    conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    question        TEXT    NOT NULL,              -- 사용자가 쓴 질문
    understood      TEXT    NOT NULL,              -- 이전 대화를 보고 이해한 질문
    answer          TEXT    NOT NULL,              -- AI 정리 (실패했으면 오류 메시지)
    quick           TEXT,                          -- 빠른 답 (JSON)
    sources         TEXT    NOT NULL DEFAULT '[]', -- 출처 목록 (JSON)
    cited           TEXT    NOT NULL DEFAULT '[]', -- 답에 쓰인 출처 번호 (JSON)
    dropped         INTEGER NOT NULL DEFAULT 0,    -- 근거가 없어서 뺀 문장 수
    seconds         REAL,                          -- 걸린 시간
    ok              INTEGER NOT NULL DEFAULT 1,    -- 1 = 성공, 0 = 오류
    created_at      TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_turns_conversation ON turns(conversation_id, id);
"""

# Postgres 는 자동 번호와 '대소문자 무시' 쓰는 법이 SQLite 와 달라요. 뜻은 위와 같아요
POSTGRES_SCHEMA = [
    """CREATE TABLE IF NOT EXISTS users (
        id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username      TEXT NOT NULL,
        password_hash TEXT NOT NULL,
        created_at    TEXT NOT NULL
    )""",
    # 대소문자가 달라도 같은 아이디로 봐요 (소문자로 바꾼 값이 겹치면 안 돼요)
    "CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower ON users (lower(username))",
    """CREATE TABLE IF NOT EXISTS conversations (
        id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        title      TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
    )""",
    "CREATE INDEX IF NOT EXISTS idx_conversations_user ON conversations(user_id, updated_at)",
    """CREATE TABLE IF NOT EXISTS turns (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
        question        TEXT NOT NULL,
        understood      TEXT NOT NULL,
        answer          TEXT NOT NULL,
        quick           TEXT,
        sources         TEXT NOT NULL DEFAULT '[]',
        cited           TEXT NOT NULL DEFAULT '[]',
        dropped         INTEGER NOT NULL DEFAULT 0,
        seconds         DOUBLE PRECISION,
        ok              INTEGER NOT NULL DEFAULT 1,
        created_at      TEXT NOT NULL
    )""",
    "CREATE INDEX IF NOT EXISTS idx_turns_conversation ON turns(conversation_id, id)",
]


def _now() -> str:
    return datetime.datetime.now().isoformat(timespec="seconds")


def _postgres() -> bool:
    return DATABASE_URL.startswith(("postgres://", "postgresql://"))


def _connect_postgres():
    """Neon 같은 Postgres 에 연결해요. 인터넷을 지나가니까 항상 암호화(SSL)해요."""
    import pg8000.dbapi  # Postgres 를 쓸 때만 불러와요 (BSD 라이선스)

    pg8000.dbapi.paramstyle = "qmark"  # SQLite 처럼 ? 자리에 값을 넣어요
    url = urlparse(DATABASE_URL)
    # 내 컴퓨터에서 시험할 때만 주소에 sslmode=disable 을 붙여서 암호화를 끌 수 있어요
    no_ssl = parse_qs(url.query).get("sslmode") == ["disable"]
    return pg8000.dbapi.connect(
        user=unquote(url.username or ""),
        password=unquote(url.password or "") or None,
        host=url.hostname,
        port=url.port or 5432,
        database=url.path.lstrip("/") or "postgres",
        ssl_context=None if no_ssl else ssl.create_default_context(),
        timeout=20,
    )


@contextmanager
def connect():
    """DB를 열고, 일이 끝나면 저장하고 닫아요. 중간에 문제가 생기면 하던 일을 취소해요."""
    if _postgres():
        conn = _connect_postgres()
    else:
        conn = sqlite3.connect(DB_PATH, timeout=10)
        conn.execute("PRAGMA foreign_keys = ON")  # 회원을 지우면 그 사람의 대화도 함께 지워져요
    try:
        yield conn
        conn.commit()
    except BaseException:
        conn.rollback()
        raise
    finally:
        conn.close()


def _run(conn, sql: str, params: tuple = ()):
    """SQL 한 줄을 실행해요. 두 DB 모두 같은 방법으로 쓸 수 있게 cursor 를 써요."""
    cursor = conn.cursor()
    cursor.execute(sql, params)
    return cursor


def _rows(cursor) -> list[dict]:
    """결과를 [{"열 이름": 값}, ...] 모양으로 바꿔요."""
    names = [d[0] for d in cursor.description]
    return [dict(zip(names, row)) for row in cursor.fetchall()]


def _one(cursor) -> dict | None:
    rows = _rows(cursor)
    return rows[0] if rows else None


def init() -> None:
    """처음 실행할 때 표를 만들어요. 이미 있으면 그대로 둬요."""
    if _postgres():
        with connect() as conn:
            for statement in POSTGRES_SCHEMA:
                _run(conn, statement)
        return
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    with connect() as conn:
        conn.execute("PRAGMA journal_mode = WAL")  # 읽기와 쓰기가 서로 덜 기다리게 해요
        conn.executescript(SQLITE_SCHEMA)


# ---------------------------------------------------------------------------
# 회원
# ---------------------------------------------------------------------------

def _is_duplicate(error: Exception) -> bool:
    """'이미 있는 값' 오류인지 알아봐요. (Postgres 는 오류 번호 23505 예요)"""
    return isinstance(error, sqlite3.IntegrityError) or "23505" in str(error)


def create_user(username: str, password_hash: str) -> int | None:
    """회원을 만들고 번호를 돌려줘요. 이미 있는 아이디면 None 을 돌려줘요."""
    try:
        with connect() as conn:
            cursor = _run(
                conn,
                "INSERT INTO users (username, password_hash, created_at) VALUES (?, ?, ?) RETURNING id",
                (username, password_hash, _now()),
            )
            return cursor.fetchone()[0]
    except Exception as e:
        if _is_duplicate(e):
            return None
        raise


def find_user(username: str) -> dict | None:
    with connect() as conn:
        return _one(_run(conn, "SELECT * FROM users WHERE lower(username) = lower(?)", (username,)))


def get_user(user_id: int) -> dict | None:
    with connect() as conn:
        return _one(_run(conn, "SELECT * FROM users WHERE id = ?", (user_id,)))


# ---------------------------------------------------------------------------
# 대화방
# ---------------------------------------------------------------------------

def create_conversation(user_id: int, title: str) -> int:
    now = _now()
    with connect() as conn:
        cursor = _run(
            conn,
            "INSERT INTO conversations (user_id, title, created_at, updated_at) VALUES (?, ?, ?, ?) RETURNING id",
            (user_id, title, now, now),
        )
        return cursor.fetchone()[0]


def list_conversations(user_id: int) -> list[dict]:
    """이 회원의 대화방 목록 (최근에 쓴 것부터)."""
    with connect() as conn:
        return _rows(_run(
            conn,
            "SELECT id, title, updated_at FROM conversations WHERE user_id = ? ORDER BY updated_at DESC, id DESC",
            (user_id,),
        ))


def owns_conversation(user_id: int, conversation_id: int) -> bool:
    """이 대화방이 이 회원 것인지 확인해요. 남의 대화는 볼 수 없어야 해요."""
    with connect() as conn:
        row = _one(_run(
            conn, "SELECT id FROM conversations WHERE id = ? AND user_id = ?", (conversation_id, user_id)
        ))
    return row is not None


def delete_conversation(user_id: int, conversation_id: int) -> bool:
    """대화방과 그 안의 기록을 지워요. 지웠으면 True."""
    with connect() as conn:
        cursor = _run(
            conn, "DELETE FROM conversations WHERE id = ? AND user_id = ?", (conversation_id, user_id)
        )
        return cursor.rowcount > 0


# ---------------------------------------------------------------------------
# 질문과 답 (검색 기록)
# ---------------------------------------------------------------------------

def _turn_to_dict(turn: dict) -> dict:
    turn["quick"] = json.loads(turn["quick"]) if turn["quick"] else None
    turn["sources"] = json.loads(turn["sources"])
    turn["cited"] = json.loads(turn["cited"])
    turn["ok"] = bool(turn["ok"])
    return turn


def get_turns(conversation_id: int) -> list[dict]:
    with connect() as conn:
        rows = _rows(_run(conn, "SELECT * FROM turns WHERE conversation_id = ? ORDER BY id", (conversation_id,)))
    return [_turn_to_dict(r) for r in rows]


def recent_history(conversation_id: int, limit: int = 2) -> list[dict]:
    """이어지는 질문을 이해할 때 쓸 최근 대화 (성공한 것만, 오래된 것부터)."""
    with connect() as conn:
        rows = _rows(_run(
            conn,
            "SELECT understood, answer FROM turns WHERE conversation_id = ? AND ok = 1 ORDER BY id DESC LIMIT ?",
            (conversation_id, limit),
        ))
    # 이전 질문은 '이해한 질문'을 써요. "그럼 토성은?" 보다 "토성의 위성은 몇 개야?"가 뜻이 분명해요
    return [{"question": r["understood"], "answer": r["answer"]} for r in reversed(rows)]


def add_turn(conversation_id: int, question: str, understood: str, answer: str, *,
             quick: dict | None = None, result: dict | None = None,
             seconds: float | None = None, ok: bool = True) -> int:
    """질문과 답을 저장하고, 대화방의 '최근 사용 시각'을 바꿔요."""
    result = result or {}
    now = _now()
    with connect() as conn:
        cursor = _run(
            conn,
            "INSERT INTO turns (conversation_id, question, understood, answer, quick, sources, cited, "
            "dropped, seconds, ok, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id",
            (
                conversation_id, question, understood, answer,
                json.dumps(quick, ensure_ascii=False) if quick else None,
                json.dumps(result.get("sources", []), ensure_ascii=False),
                json.dumps(result.get("cited", [])),
                len(result.get("dropped", [])),
                round(seconds, 1) if seconds is not None else None,
                int(ok), now,
            ),
        )
        turn_id = cursor.fetchone()[0]
        _run(conn, "UPDATE conversations SET updated_at = ? WHERE id = ?", (now, conversation_id))
        return turn_id
